services:

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  aws:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    volumes: # https://docs.localstack.cloud/references/init-hooks/
      - ".localstack/bootstrap:/etc/localstack/init/ready.d/"
